import * as path from 'path';
import {
  getBaseDir,
  getFaqFileName,
  requireWorkspaceRoot,
  writeFile,
  readFileOrNull,
} from './fileUtils';

const FAQ_STARTER = `# AI FAQ — Recurring Knowledge Base

> Auto-generated by AI Archive. Add your own entries below.

---

## Common Problems

<!-- Describe recurring issues and their root causes here. -->

---

## Preferred Solutions

<!-- Document approaches and patterns that work well in this project. -->

---

## Reusable Prompts

<!-- Store prompt templates that yield good results. -->

---
`;

/**
 * Ensures the FAQ file exists.  Creates it with starter sections if not.
 * Returns the absolute path to the FAQ file.
 */
export function ensureFaqFile(): string {
  const root = requireWorkspaceRoot();
  const faqPath = path.join(root, getBaseDir(), getFaqFileName());
  if (!readFileOrNull(faqPath)) {
    writeFile(faqPath, FAQ_STARTER);
  }
  return faqPath;
}
